<?php

namespace ContainerRHCwxjy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KPJs7pService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.kPJs_7p' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kPJs_7p'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'taskRepo' => ['privates', 'App\\Repository\\TaskRepository', 'getTaskRepositoryService', true],
            'todolistRepo' => ['privates', 'App\\Repository\\TodolistRepository', 'getTodolistRepositoryService', true],
        ], [
            'em' => '?',
            'taskRepo' => 'App\\Repository\\TaskRepository',
            'todolistRepo' => 'App\\Repository\\TodolistRepository',
        ]);
    }
}
