<?php

namespace ContainerRHCwxjy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddListTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\AddListType' shared autowired service.
     *
     * @return \App\Form\AddListType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\AddListType'] = new \App\Form\AddListType();
    }
}
