<?php

namespace ContainerRHCwxjy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEditControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\EditController' shared autowired service.
     *
     * @return \App\Controller\EditController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\EditController'] = $instance = new \App\Controller\EditController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\EditController', $container));

        return $instance;
    }
}
