<?php

namespace ContainerRHCwxjy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailer_MessageListenerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'mailer.message_listener' shared service.
     *
     * @return \Symfony\Component\Mailer\EventListener\MessageListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = new \Symfony\Component\Mime\Header\Headers();
        $a->addHeader('From', ['TODO app <symfony@server054599.nazwa.pl>']);

        return $container->privates['mailer.message_listener'] = new \Symfony\Component\Mailer\EventListener\MessageListener($a);
    }
}
