<?php

namespace ContainerRHCwxjy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTodolistRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\TodolistRepository' shared autowired service.
     *
     * @return \App\Repository\TodolistRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\TodolistRepository'] = new \App\Repository\TodolistRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
