<?php

namespace ContainerRHCwxjy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserRegisterTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\UserRegisterType' shared autowired service.
     *
     * @return \App\Form\UserRegisterType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\UserRegisterType'] = new \App\Form\UserRegisterType();
    }
}
