<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRHCwxjy\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRHCwxjy/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerRHCwxjy.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerRHCwxjy\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerRHCwxjy\App_KernelProdContainer([
    'container.build_hash' => 'RHCwxjy',
    'container.build_id' => '831db826',
    'container.build_time' => 1690885451,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRHCwxjy');
