<?php

namespace ContainerN65lxei;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SmnS_NDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.smnS.ND' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.smnS.ND'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator(
            $container->getService ??= $container->getService(...), [
            'task' => ['privates', '.errored..service_locator.smnS.ND.App\\Entity\\Task', null, 'Cannot autowire service ".service_locator.smnS.ND": it needs an instance of "App\\Entity\\Task" but this type has been excluded in "config/services.yaml".'],
            'taskRepo' => ['privates', 'App\\Repository\\TaskRepository', 'getTaskRepositoryService', true],
            ], [
            'task' => 'App\\Entity\\Task',
            'taskRepo' => 'App\\Repository\\TaskRepository',
            ]
        );
    }
}
