<?php

namespace ContainerN65lxei;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_D4b5SpvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.d4b5Spv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.d4b5Spv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator(
            $container->getService ??= $container->getService(...), [
            'taskRepo' => ['privates', 'App\\Repository\\TaskRepository', 'getTaskRepositoryService', true],
            'todolistRepo' => ['privates', 'App\\Repository\\TodolistRepository', 'getTodolistRepositoryService', true],
            ], [
            'taskRepo' => 'App\\Repository\\TaskRepository',
            'todolistRepo' => 'App\\Repository\\TodolistRepository',
            ]
        );
    }
}
