<?php

namespace ContainerN65lxei;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GQzPcTjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gQzPcTj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gQzPcTj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator(
            $container->getService ??= $container->getService(...), [
            'taskRepo' => ['privates', 'App\\Repository\\TaskRepository', 'getTaskRepositoryService', true],
            'todolist' => ['privates', '.errored..service_locator.gQzPcTj.App\\Entity\\Todolist', null, 'Cannot autowire service ".service_locator.gQzPcTj": it needs an instance of "App\\Entity\\Todolist" but this type has been excluded in "config/services.yaml".'],
            'todolistRepo' => ['privates', 'App\\Repository\\TodolistRepository', 'getTodolistRepositoryService', true],
            ], [
            'taskRepo' => 'App\\Repository\\TaskRepository',
            'todolist' => 'App\\Entity\\Todolist',
            'todolistRepo' => 'App\\Repository\\TodolistRepository',
            ]
        );
    }
}
