<?php

namespace ContainerN65lxei;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_QJMgL0yService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.qJMgL0y' shared service.
     *
     * @return \App\Controller\MessageBusInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\SecurityController::register()": the $bus argument is type-hinted with the non-existent class or interface: "App\\Controller\\MessageBusInterface". Did you forget to add a use statement?');
    }
}
