<?php

namespace ContainerN65lxei;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_PTIKQrZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.PTIKQrZ' shared service.
     *
     * @return \App\Controller\BodyRendererInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\SecurityController::register()": the $bodyRenderer argument is type-hinted with the non-existent class or interface: "App\\Controller\\BodyRendererInterface". Did you forget to add a use statement?');
    }
}
