<?php

namespace ContainerN65lxei;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTodolistService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.gQzPcTj.App\Entity\Todolist' shared service.
     *
     * @return \App\Entity\Todolist
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.gQzPcTj": it needs an instance of "App\\Entity\\Todolist" but this type has been excluded in "config/services.yaml".');
    }
}
