<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGN4q24q\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGN4q24q/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGN4q24q.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGN4q24q\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGN4q24q\App_KernelDevDebugContainer(
    [
    'container.build_hash' => 'GN4q24q',
    'container.build_id' => 'f4068925',
    'container.build_time' => 1690803114,
    ], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGN4q24q'
);
