<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app.create_new_list' => [[], ['_controller' => 'App\\Controller\\CreateController::createNewList'], [], [['text', '/lists/createnewlist']], [], [], []],
    'app.add_new_task' => [['listname'], ['_controller' => 'App\\Controller\\CreateController::createNewTask'], [], [['variable', '/', '[^/]++', 'listname', true], ['text', '/lists/addnewtask']], [], [], []],
    'app.remove_list' => [['listname'], ['_controller' => 'App\\Controller\\CreateController::removeList'], [], [['variable', '/', '[^/]++', 'listname', true], ['text', '/lists/removelist']], [], [], []],
    'app.remove_task' => [['id'], ['_controller' => 'App\\Controller\\CreateController::removeTask'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/lists/removetask']], [], [], []],
    'app.edit_list' => [['listname'], ['_controller' => 'App\\Controller\\EditController::editList'], [], [['variable', '/', '[^/]++', 'listname', true], ['text', '/lists/edit']], [], [], []],
    'app.edit_task' => [['listname', 'id'], ['_controller' => 'App\\Controller\\EditController::editTask'], [], [['variable', '/', '[^/]++', 'id', true], ['variable', '/', '[^/]++', 'listname', true], ['text', '/lists/edit']], [], [], []],
    'app.finished' => [['id', 'finished'], ['_controller' => 'App\\Controller\\EditController::setFinished'], [], [['variable', '/', '[^/]++', 'finished', true], ['variable', '/', '[^/]++', 'id', true], ['text', '/lists/change']], [], [], []],
    'app.lists' => [[], ['_controller' => 'App\\Controller\\MainController::showLists'], [], [['text', '/lists/']], [], [], []],
    'app.all_tasks' => [['listname'], ['_controller' => 'App\\Controller\\MainController::showTasks'], [], [['variable', '/', '[^/]++', 'listname', true], ['text', '/lists']], [], [], []],
    'app.one_task' => [['listname', 'id'], ['_controller' => 'App\\Controller\\MainController::showOneTask'], [], [['variable', '/', '[^/]++', 'id', true], ['variable', '/', '[^/]++', 'listname', true], ['text', '/lists']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\SecurityController::register'], [], [['text', '/register']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
];
